apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-petclinic.fullname" . }}
  namespace: petclinic
  labels:
    {{- include "spring-petclinic.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "spring-petclinic.selectorLabels" . | nindent 4 }}
