AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Permisos adicionales para EKS MCP: AutoScaling, Node Groups y EC2 Launch Templates.
  Complementa la policy principal.

Parameters:
  PolicyName:
    Type: String
    Default: AmazonQDeveloperEKSMCPAdditionalPolicy
    Description: Nombre de la policy adicional para Node Groups.
  RolePath:
    Type: String
    Default: /
    Description: Path opcional para la policy.

Resources:
  AdditionalManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref PolicyName
      Path: !Ref RolePath
      Description: Permisos adicionales para EKS Node Groups, AutoScaling y Launch Templates.
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ECRBuildAndPush
            Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
              - ecr:CreateRepository
              - ecr:DescribeRepositories
              - ecr:ListImages
              - ecr:DescribeImages
              - ecr:BatchCheckLayerAvailability
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
              - ecr:PutImage
              - ecr:BatchGetImage
              - ecr:GetDownloadUrlForLayer
              - ecr:DeleteRepository
              - ecr:SetRepositoryPolicy
              - ecr:DeleteRepositoryPolicy
            Resource: "*"

          - Sid: AutoScalingForNodeGroups
            Effect: Allow
            Action:
              - autoscaling:CreateAutoScalingGroup
              - autoscaling:UpdateAutoScalingGroup
              - autoscaling:DeleteAutoScalingGroup
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribeAutoScalingInstances
              - autoscaling:DescribeLaunchConfigurations
              - autoscaling:DescribeScalingActivities
              - autoscaling:CreateLaunchConfiguration
              - autoscaling:DeleteLaunchConfiguration
              - autoscaling:SetDesiredCapacity
              - autoscaling:TerminateInstanceInAutoScalingGroup
              - autoscaling:CreateOrUpdateTags
              - autoscaling:DeleteTags
              - autoscaling:DescribeTags
              - autoscaling:EnableMetricsCollection
              - autoscaling:DisableMetricsCollection
              - autoscaling:SuspendProcesses
              - autoscaling:ResumeProcesses
            Resource: "*"

          - Sid: EKSNodeGroupManagement
            Effect: Allow
            Action:
              - eks:CreateNodegroup
              - eks:DeleteNodegroup
              - eks:DescribeNodegroup
              - eks:ListNodegroups
              - eks:UpdateNodegroupConfig
              - eks:UpdateNodegroupVersion
            Resource: "*"

          - Sid: EC2LaunchTemplates
            Effect: Allow
            Action:
              - ec2:CreateLaunchTemplate
              - ec2:CreateLaunchTemplateVersion
              - ec2:DeleteLaunchTemplate
              - ec2:DeleteLaunchTemplateVersions
              - ec2:DescribeLaunchTemplates
              - ec2:DescribeLaunchTemplateVersions
              - ec2:ModifyLaunchTemplate
              - ec2:DescribeInstanceTypes
              - ec2:DescribeInstanceAttribute
              - ec2:ModifyInstanceAttribute
            Resource: "*"

          - Sid: EC2InstanceManagement
            Effect: Allow
            Action:
              - ec2:RunInstances
              - ec2:TerminateInstances
              - ec2:DescribeInstances
              - ec2:DescribeVolumes
              - ec2:DescribeSnapshots
              - ec2:DescribeImages
              - ec2:DescribeKeyPairs
            Resource: "*"

Outputs:
  AdditionalPolicyArn:
    Description: ARN de la policy adicional para adjuntar al Permission Set de SSO.
    Value: !Ref AdditionalManagedPolicy
